/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {
        System.out.println("Hello tic tac toe");
        Grid grid = new Grid();
        grid.printGrid();
    }
}
