/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.controller.GameController;
import org.example.model.tictactoe.TicTacToe;
import org.example.model.tictactoe.TicTacToeImpl;
import org.example.view.View;

public class App {

    public static void main(String[] args) {
        System.out.println("Hello tic tac toe");
        View view = new View();
        TicTacToe game = new TicTacToeImpl();
        GameController controller = new GameController(view, game);
        view.setController(controller);

        controller.startGui();
    }
}
