/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.model.TicTacToeImpl;

public class App {

    public static void main(String[] args) {
        System.out.println("Hello tic tac toe");
        TicTacToeImpl grid = new TicTacToeImpl();
        grid.printGrid();
    }
}
